apiVersion: v1
kind: Service
metadata:
  name: farmworld-vue-backend
  labels:
    app: farmworld-vue-backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: farmworld-vue-backend
  type: LoadBalancer
