name: Base Image

on:
  push:
    branches:
      - develop
    # branches-ignore:
    #  - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: GitHub Environment Variables Action
        id: env-vars
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Build Docker image
        env:
          IMAGE_TAG: base
        run: docker build . --file Dockerfile.base --tag asia-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/asia.gcr.io/$CI_REPOSITORY_NAME_SLUG:$IMAGE_TAG

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      - name: Configure Docker to use Google Cloud Platform
        run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker asia-docker.pkg.dev

      - name: Push image to Google Cloud Container Registry
        env:
          IMAGE_TAG: base
        run: |
          docker push asia-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/asia.gcr.io/$CI_REPOSITORY_NAME_SLUG:base
