name: Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: GitHub Environment Variables Action
        id: env-vars
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      - name: Configure Docker to use Google Cloud Platform
        run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker asia-docker.pkg.dev

      - name: Build Docker image
        run: docker build . --file Dockerfile.prod  --tag asia-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/asia.gcr.io/$CI_REPOSITORY_NAME_SLUG:${{ steps.bump_version.outputs.new_tag }}

      - name: Push image to Google Cloud Container Registry
        run: |
          docker push asia-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/asia.gcr.io/$CI_REPOSITORY_NAME_SLUG:${{ steps.bump_version.outputs.new_tag }}

      - name: Extract tag name
        id: tag_template
        uses: frabert/replace-string-action@v2.2
        with:
          pattern: (\.+)
          string: ${{ steps.bump_version.outputs.new_tag }}
          replace-with: '-'
          flags: g

      - name: Configure Docker to use Google Cloud Platform
        run: |
          gcloud config set project farmpress-production &&\
          gcloud config set compute/zone asia-southeast1-b &&\
          gcloud config set compute/region asia-southeast1 &&\
          gcloud compute instance-templates create-with-container \
          $CI_REPOSITORY_NAME_SLUG-${{ steps.tag_template.outputs.replaced }} \
          --machine-type e2-small \
          --image-family cos-stable \
          --image-project cos-cloud \
          --container-image asia-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/asia.gcr.io/$CI_REPOSITORY_NAME_SLUG:${{ steps.bump_version.outputs.new_tag }} \
          --container-privileged \
          --boot-disk-size 20 \
          --boot-disk-type pd-balanced \
          --tags 'http8080,http-server,https-server' \
          --scopes 'default' \
          --metadata startup-script='#! /bin/bash
          docker image prune -fa'
