trigger:
  branches:
    include:
      - libs

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: main-iot
  - name: ecr_repo
    value: 350474780471.dkr.ecr.ap-southeast-1.amazonaws.com
  - name: project
    value: iot-vue-backend

stages:
  - stage: build_stage
    displayName: Build stage
    jobs:
      - job: build_job
        displayName: Build Job
        steps:
          - bash: |
              export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID_ECR)
              export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY_ECR)
              aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $(ecr_repo)
            displayName: Login to the ECR

          - bash: docker build -f Dockerfile.libs . -t $(ecr_repo)/$(project):libs
            displayName: Containerize

          - bash: docker push $(ecr_repo)/$(project):libs
            displayName: Push to the ECR
